### ISSUE TITLE
TypeError: get_coreclr() takes 0 positional arguments

### ISSUE THREAD

**Issue by JunkBeat** [jrobinson3k1/typetree_unity#4]
cmd /k python -m typetree_unity "D:\Game\Game_Data\Managed" "5.4.2.2"

I am getting the following error:
 File "C:\Users\name\Desktop\typetree_unity-master\typetree_unity\clr\assembly_loader.py", line 16, in load
    get_coreclr(
TypeError: get_coreclr() takes 0 positional arguments but 1 was given

**Comment by kizukkk** [comment]
I changed the following code block in the assembly_loader.py file and it helped me:
   ```
 set_runtime(
        get_coreclr( runtime_config = 
            os.path.join(
                lib_dir,
                "runtimeconfig.json"
            )
        )
    )
```
